import { useEffect, useRef, useState } from 'react';
import { ArrowRight, Check, Lightbulb, RotateCcw, X } from 'lucide-react';
import { checkAnswer, type Exercise } from '../lib/exercises';
import type { ReviewRating } from '../lib/scheduler';
import { AudioButton, ProgressBar } from './ui';
import { stopAudio } from '../lib/audio';
export function ExerciseRunner({exercises,title,onResult,onComplete,onClose}:{exercises:Exercise[];title:string;onResult:(e:Exercise,r:ReviewRating)=>void;onComplete:()=>void;onClose:()=>void}){
 const [queue,setQueue]=useState(exercises),[index,setIndex]=useState(0),[answer,setAnswer]=useState(''),[checked,setChecked]=useState(false),[correct,setCorrect]=useState(false),[hint,setHint]=useState(false),[selected,setSelected]=useState<number[]>([]),[done,setDone]=useState(false),[score,setScore]=useState(0),[error,setError]=useState('');
 const repeated=useRef(new Set<string>());const advancing=useRef(false);const input=useRef<HTMLInputElement>(null);const e=queue[index];
 useEffect(()=>()=>stopAudio(),[]);
 useEffect(()=>{window.scrollTo(0,0);setAnswer('');setSelected([]);setChecked(false);setCorrect(false);setHint(false);advancing.current=false;},[index]);
 const submit=()=>{if(checked||!answer.trim())return;setCorrect(e.kind==='self'?false:checkAnswer(e,answer));setChecked(true);};
 const finish=(rating:ReviewRating)=>{if(advancing.current)return;advancing.current=true;try{onResult(e,rating);}catch(err){setError((err as Error).message);advancing.current=false;return;}
   if(rating!=='again')setScore(n=>n+1);
   let length=queue.length;
   if(rating==='again'&&!repeated.current.has(e.id)){repeated.current.add(e.id);const next=[...queue];next.splice(Math.min(index+3,next.length),0,e);setQueue(next);length++;}
   if(index+1>=length){setDone(true);onComplete();}else setIndex(index+1);
 };
 if(!e||done)return <div className="session-done"><div className="done-mark"><Check size={36}/></div><span className="eyebrow">Lerneinheit beendet</span><h1>Gut für heute.</h1><p>Du hast {queue.length} Aufgaben bearbeitet. {score} Antworten konntest du abrufen.</p><p className="muted">Deine Antworten bestimmen, wann die nächsten Wiederholungen sinnvoll sind.</p><button className="button primary" onClick={onClose}>Zur Übersicht <ArrowRight size={18}/></button></div>;
 return <div className="study-shell"><div className="study-top"><span>{title}</span><button className="icon-button" onClick={()=>{if(window.confirm('Lerneinheit verlassen? Bereits beantwortete Aufgaben bleiben gespeichert.'))onClose();}} aria-label="Lerneinheit verlassen"><X/></button></div><ProgressBar value={index} max={queue.length} label={`Aufgabe ${index+1} von ${queue.length}`}/><div className="exercise-card" key={`${index}-${e.id}`}><span className="eyebrow">{e.skill==='listening'?'Hören':e.skill==='production'?'Aktiv formulieren':e.skill==='pinyin'?'Aussprache':e.skill==='context'?'Im Zusammenhang':'Bedeutung abrufen'}</span><h1 className="exercise-prompt">{e.prompt}</h1>{e.zh&&<p className={`chinese exercise-zh ${e.zh.length>12?'sentence':''}`} lang="zh-CN">{e.zh}</p>}{e.audio&&<div className="listen-area"><AudioButton text={e.audio} label="Anhören"/></div>}
 {e.pinyin&&e.kind!=='order'&&!checked&&<div className="hint"><button className="text-button" onClick={()=>setHint(true)}><Lightbulb size={16}/> {hint?e.pinyin:'Pinyin als Hilfe'}</button></div>}
 {e.kind==='choice'?<div className="choices">{e.options?.map((option,i)=><button key={i} className={`choice ${answer===option?'selected':''} ${checked&&option===e.answer?'correct':''}`} disabled={checked} onClick={()=>setAnswer(option)}><span className="choice-letter">{String.fromCharCode(65+i)}</span><span>{option}</span>{checked&&option===e.answer&&<Check size={18}/>}</button>)}</div>:e.kind==='order'?<><p className="muted">{e.pinyin}</p><div className="order-answer chinese" lang="zh-CN">{answer||'…'}</div><div className="token-bank">{e.tokens?.map((t,i)=><button className="token chinese" key={i} disabled={selected.includes(i)||checked} onClick={()=>{setSelected([...selected,i]);setAnswer(answer+t);}} lang="zh-CN">{t}</button>)}</div><button className="text-button" disabled={checked} onClick={()=>{setAnswer('');setSelected([]);}}><RotateCcw size={16}/> Neu ordnen</button></>:<form onSubmit={ev=>{ev.preventDefault();submit();}}><label htmlFor="answer-input" className="input-label">{e.skill==='pinyin'?'Pinyin mit Tonzeichen oder Tonziffern':e.skill==='production'?'Deine Antwort auf Chinesisch oder in Pinyin':'Deine Antwort auf Deutsch'}</label><input id="answer-input" ref={input} autoComplete="off" autoCapitalize="off" spellCheck={false} value={answer} onChange={ev=>setAnswer(ev.target.value)} disabled={checked} placeholder={e.skill==='pinyin'?'z. B. nǐ hǎo oder ni3 hao3':'Erinnere dich zuerst …'}/>{(e.skill==='pinyin'||e.skill==='production')&&!checked&&<div className="tone-keyboard">{'āáǎàēéěèīíǐìōóǒòūúǔùüǖǘǚǜ'.split('').map(c=><button key={c} type="button" onClick={()=>{const start=input.current?.selectionStart??answer.length;setAnswer(answer.slice(0,start)+c+answer.slice(start));input.current?.focus();}}>{c}</button>)}</div>}</form>}
 {!checked?<div className="exercise-actions"><button className="button primary" disabled={!answer.trim()} onClick={submit}>{e.kind==='self'?'Mit Beispiel vergleichen':'Antwort prüfen'} <ArrowRight size={18}/></button><button className="text-button" onClick={()=>{setChecked(true);setCorrect(false);}}>Ich weiß es noch nicht</button></div>:<div className={`feedback ${correct?'success':'learning'}`} role="status"><h2>{e.kind==='self'?'Vergleiche deine Formulierung.':correct?'Richtig erinnert.':'Hier ist die Lösung.'}</h2><p className="feedback-solution">{e.explanation}</p>{!correct&&e.kind!=='self'&&<p className="small">Dieser Inhalt kommt in dieser Einheit noch einmal vor und wird früher wiederholt.</p>}<div className="rating-buttons">{correct?<><button className="button secondary" onClick={()=>finish('hard')}>Mit Mühe</button><button className="button primary" onClick={()=>finish(hint?'hard':'good')}>Gewusst <ArrowRight size={18}/></button>{!hint&&<button className="button secondary" onClick={()=>finish('easy')}>Leicht</button>}</>:<><button className="button primary" onClick={()=>finish('again')}>Weiter üben <ArrowRight size={18}/></button>{answer.trim()&&e.kind!=='choice'&&e.kind!=='order'&&<button className="button secondary" onClick={()=>finish('hard')}>{e.kind==='self'?'Sinngemäß richtig':'Meine Antwort stimmt sinngemäß'}</button>}</>}</div></div>}{error&&<p className="error" role="alert">{error}</p>}</div></div>;
}
